<?php
// Simple PDF generator for testing — outputs a PDF with "hello world" and forces download
require_once __DIR__ . '/../../vendor/autoload.php';
use Dompdf\Dompdf;

try {
    $dompdf = new Dompdf();
    $html = '<!doctype html><html><head><meta charset="utf-8"><style>body{font-family: DejaVu Sans, Arial, sans-serif;}</style></head><body><h1>Hello World</h1><p>This is a test PDF generated by Dompdf.</p></body></html>';
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    // Stream the PDF as a download
    $dompdf->stream('hello_world.pdf', ['Attachment' => 1]);
    exit;
} catch (Exception $e) {
    header('Content-Type: text/plain', true, 500);
    echo 'PDF generation failed: ' . $e->getMessage();
    exit;
}

?>
